# Generated by Django 5.0.12 on 2025-02-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NNPTable1',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('data_type', models.CharField(max_length=255)),
                ('platform_seq', models.CharField(max_length=255)),
                ('NCBI_ID', models.CharField(max_length=255)),
                ('studied_nutrient', models.CharField(max_length=255)),
                ('growing_seasons', models.CharField(max_length=255)),
                ('Tissue', models.CharField(max_length=255)),
                ('Genotype_name', models.CharField(max_length=255)),
                ('trait_studied', models.CharField(max_length=255)),
                ('study', models.CharField(max_length=255)),
                ('summary_abstract', models.TextField()),
            ],
            options={
                'db_table': 'NNPTable1',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='NutrientStudy',
        ),
    ]
